<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250129125743 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE messenger_messages_id_seq CASCADE');
        $this->addSql('CREATE TABLE recipes_ingredients (recipes_id INT NOT NULL, ingredients_id INT NOT NULL, PRIMARY KEY(recipes_id, ingredients_id))');
        $this->addSql('CREATE INDEX IDX_761206B0FDF2B1FA ON recipes_ingredients (recipes_id)');
        $this->addSql('CREATE INDEX IDX_761206B03EC4DCE ON recipes_ingredients (ingredients_id)');
        $this->addSql('ALTER TABLE recipes_ingredients ADD CONSTRAINT FK_761206B0FDF2B1FA FOREIGN KEY (recipes_id) REFERENCES recipes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipes_ingredients ADD CONSTRAINT FK_761206B03EC4DCE FOREIGN KEY (ingredients_id) REFERENCES ingredients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE dishes ALTER id TYPE INT');
        $this->addSql('ALTER TABLE dishes ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE ingredients DROP CONSTRAINT fk_4b60114f12469de2');
        $this->addSql('DROP INDEX idx_4b60114f12469de2');
        $this->addSql('ALTER TABLE ingredients ALTER id TYPE INT');
        $this->addSql('ALTER TABLE ingredients ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE ingredients RENAME COLUMN category_id TO id_category_id');
        $this->addSql('ALTER TABLE ingredients ADD CONSTRAINT FK_4B60114FA545015 FOREIGN KEY (id_category_id) REFERENCES ingredients_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_4B60114FA545015 ON ingredients (id_category_id)');
        $this->addSql('ALTER TABLE ingredients_category ALTER id TYPE INT');
        $this->addSql('ALTER TABLE ingredients_category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE recipes DROP CONSTRAINT fk_a369e2b53ec4dce');
        $this->addSql('DROP INDEX idx_a369e2b53ec4dce');
        $this->addSql('ALTER TABLE recipes DROP ingredients_id');
        $this->addSql('ALTER TABLE recipes ALTER id TYPE INT');
        $this->addSql('ALTER TABLE recipes ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE messenger_messages_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT DEFAULT messenger_messages_id_seq NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE recipes_ingredients DROP CONSTRAINT FK_761206B0FDF2B1FA');
        $this->addSql('ALTER TABLE recipes_ingredients DROP CONSTRAINT FK_761206B03EC4DCE');
        $this->addSql('DROP TABLE recipes_ingredients');
        $this->addSql('ALTER TABLE ingredients_category ALTER id TYPE INT');
        $this->addSql('ALTER TABLE ingredients_category ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE ingredients DROP CONSTRAINT FK_4B60114FA545015');
        $this->addSql('DROP INDEX IDX_4B60114FA545015');
        $this->addSql('ALTER TABLE ingredients ALTER id TYPE INT');
        $this->addSql('ALTER TABLE ingredients ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE ingredients RENAME COLUMN id_category_id TO category_id');
        $this->addSql('ALTER TABLE ingredients ADD CONSTRAINT fk_4b60114f12469de2 FOREIGN KEY (category_id) REFERENCES ingredients_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_4b60114f12469de2 ON ingredients (category_id)');
        $this->addSql('ALTER TABLE dishes ALTER id TYPE INT');
        $this->addSql('ALTER TABLE dishes ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE recipes ADD ingredients_id INT NOT NULL');
        $this->addSql('ALTER TABLE recipes ALTER id TYPE INT');
        $this->addSql('ALTER TABLE recipes ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE recipes ADD CONSTRAINT fk_a369e2b53ec4dce FOREIGN KEY (ingredients_id) REFERENCES ingredients (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_a369e2b53ec4dce ON recipes (ingredients_id)');
    }
}
