<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250128190550 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dishes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ingredients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, id_category_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4B60114FA545015 ON ingredients (id_category_id)');
        $this->addSql('CREATE TABLE ingredients_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE recipes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dish_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A369E2B5148EB0CB ON recipes (dish_id)');
        $this->addSql('CREATE TABLE recipes_ingredients (recipes_id INT NOT NULL, ingredients_id INT NOT NULL, PRIMARY KEY(recipes_id, ingredients_id))');
        $this->addSql('CREATE INDEX IDX_761206B0FDF2B1FA ON recipes_ingredients (recipes_id)');
        $this->addSql('CREATE INDEX IDX_761206B03EC4DCE ON recipes_ingredients (ingredients_id)');
        $this->addSql('ALTER TABLE ingredients ADD CONSTRAINT FK_4B60114FA545015 FOREIGN KEY (id_category_id) REFERENCES ingredients_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipes ADD CONSTRAINT FK_A369E2B5148EB0CB FOREIGN KEY (dish_id) REFERENCES dishes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipes_ingredients ADD CONSTRAINT FK_761206B0FDF2B1FA FOREIGN KEY (recipes_id) REFERENCES recipes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipes_ingredients ADD CONSTRAINT FK_761206B03EC4DCE FOREIGN KEY (ingredients_id) REFERENCES ingredients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ingredients DROP CONSTRAINT FK_4B60114FA545015');
        $this->addSql('ALTER TABLE recipes DROP CONSTRAINT FK_A369E2B5148EB0CB');
        $this->addSql('ALTER TABLE recipes_ingredients DROP CONSTRAINT FK_761206B0FDF2B1FA');
        $this->addSql('ALTER TABLE recipes_ingredients DROP CONSTRAINT FK_761206B03EC4DCE');
        $this->addSql('DROP TABLE dishes');
        $this->addSql('DROP TABLE ingredients');
        $this->addSql('DROP TABLE ingredients_category');
        $this->addSql('DROP TABLE recipes');
        $this->addSql('DROP TABLE recipes_ingredients');
    }
}
