<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250128163940 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE chief_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE client_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ingredientscategory_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE linkingredients_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE orders_id_seq CASCADE');
        $this->addSql('CREATE TABLE ingredients_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE recipes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dish_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A369E2B5148EB0CB ON recipes (dish_id)');
        $this->addSql('CREATE TABLE recipes_ingredients (recipes_id INT NOT NULL, ingredients_id INT NOT NULL, PRIMARY KEY(recipes_id, ingredients_id))');
        $this->addSql('CREATE INDEX IDX_761206B0FDF2B1FA ON recipes_ingredients (recipes_id)');
        $this->addSql('CREATE INDEX IDX_761206B03EC4DCE ON recipes_ingredients (ingredients_id)');
        $this->addSql('ALTER TABLE recipes ADD CONSTRAINT FK_A369E2B5148EB0CB FOREIGN KEY (dish_id) REFERENCES dishes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipes_ingredients ADD CONSTRAINT FK_761206B0FDF2B1FA FOREIGN KEY (recipes_id) REFERENCES recipes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipes_ingredients ADD CONSTRAINT FK_761206B03EC4DCE FOREIGN KEY (ingredients_id) REFERENCES ingredients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT orders_idclient_foreign');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT orders_iddishes_foreign');
        $this->addSql('ALTER TABLE linkingredients DROP CONSTRAINT linkingredients_idingredient_foreign');
        $this->addSql('ALTER TABLE linkingredients DROP CONSTRAINT linkingredients_iddish_foreign');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE ingredientscategory');
        $this->addSql('DROP TABLE chief');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE linkingredients');
        $this->addSql('ALTER TABLE dishes ALTER id TYPE INT');
        $this->addSql('ALTER TABLE dishes ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dishes ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dishes ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE ingredients ADD id_category_id INT NOT NULL');
        $this->addSql('ALTER TABLE ingredients DROP "idCategory"');
        $this->addSql('ALTER TABLE ingredients ALTER id TYPE INT');
        $this->addSql('ALTER TABLE ingredients ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ingredients ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE ingredients ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE ingredients ADD CONSTRAINT FK_4B60114FA545015 FOREIGN KEY (id_category_id) REFERENCES ingredients_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_4B60114FA545015 ON ingredients (id_category_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE chief_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE client_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ingredientscategory_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE linkingredients_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE orders_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE client (id INT DEFAULT client_id_seq NOT NULL, name BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ingredientscategory (id INT DEFAULT ingredientscategory_id_seq NOT NULL, name BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE chief (id INT DEFAULT chief_id_seq NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE orders (id INT DEFAULT orders_id_seq NOT NULL, "idClient" BIGINT NOT NULL, "idDishes" BIGINT NOT NULL, "Date" DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E52FFDEE42368BD1 ON orders ("idClient")');
        $this->addSql('CREATE INDEX IDX_E52FFDEE4C720A34 ON orders ("idDishes")');
        $this->addSql('CREATE TABLE linkingredients (id INT DEFAULT linkingredients_id_seq NOT NULL, "idIngredient" BIGINT NOT NULL, "idDish" BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7FA121C2E5940C65 ON linkingredients ("idIngredient")');
        $this->addSql('CREATE INDEX IDX_7FA121C29694CE7A ON linkingredients ("idDish")');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT orders_idclient_foreign FOREIGN KEY ("idClient") REFERENCES chief (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT orders_iddishes_foreign FOREIGN KEY ("idDishes") REFERENCES dishes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE linkingredients ADD CONSTRAINT linkingredients_idingredient_foreign FOREIGN KEY ("idIngredient") REFERENCES ingredients (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE linkingredients ADD CONSTRAINT linkingredients_iddish_foreign FOREIGN KEY ("idDish") REFERENCES dishes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipes DROP CONSTRAINT FK_A369E2B5148EB0CB');
        $this->addSql('ALTER TABLE recipes_ingredients DROP CONSTRAINT FK_761206B0FDF2B1FA');
        $this->addSql('ALTER TABLE recipes_ingredients DROP CONSTRAINT FK_761206B03EC4DCE');
        $this->addSql('DROP TABLE ingredients_category');
        $this->addSql('DROP TABLE recipes');
        $this->addSql('DROP TABLE recipes_ingredients');
        $this->addSql('ALTER TABLE ingredients DROP CONSTRAINT FK_4B60114FA545015');
        $this->addSql('DROP INDEX IDX_4B60114FA545015');
        $this->addSql('ALTER TABLE ingredients ADD "idCategory" BIGINT NOT NULL');
        $this->addSql('ALTER TABLE ingredients DROP id_category_id');
        $this->addSql('ALTER TABLE ingredients ALTER id TYPE INT');
        $this->addSql('ALTER TABLE ingredients ALTER id SET DEFAULT ingredients_id_seq');
        $this->addSql('ALTER TABLE ingredients ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE ingredients ALTER name TYPE BIGINT');
        $this->addSql('ALTER TABLE dishes ALTER id TYPE INT');
        $this->addSql('ALTER TABLE dishes ALTER id SET DEFAULT dishes_id_seq');
        $this->addSql('ALTER TABLE dishes ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dishes ALTER name TYPE BIGINT');
    }
}
